/*
 * generated by Xtext 2.24.0
 */
package form.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(FormDSLInjectorProvider)
class FormDSLParsingTest {
	@Inject
	//ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		//todo
	}
}
