/*
 * generated by Xtext 2.24.0
 */
package form;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FormDSLStandaloneSetup extends FormDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new FormDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
