grammar form.FormDSL with org.eclipse.xtext.common.Terminals

generate formDSL "http://www.FormDSL.form"

Form: 
	{Form}"form" content += (Input)*
;

Input:
	type = Type
	name = Name
	(expression = Expression)?
	;

Type:
	text="shortText" | text="date" | text="number" | 
	text="money" | text="email" | text="longText" | text="stringNumber"
;

Name: 
	text = STRING
;

Expression:
	text="optional" | text="focus" | text="require"
;