/**
 * generated by Xtext 2.24.0
 */
package form.generator;

import com.google.common.collect.Iterators;
import form.formDSL.Comparison;
import form.formDSL.Exactly;
import form.formDSL.Expression;
import form.formDSL.Focus;
import form.formDSL.Form;
import form.formDSL.Generic;
import form.formDSL.GreaterThan;
import form.formDSL.GreaterThanInclusive;
import form.formDSL.Input;
import form.formDSL.Is;
import form.formDSL.Length;
import form.formDSL.LessThan;
import form.formDSL.LessThanInclusive;
import form.formDSL.LongText;
import form.formDSL.Money;
import form.formDSL.Name;
import form.formDSL.Not;
import form.formDSL.Optional;
import form.formDSL.ShortText;
import form.formDSL.StringNumber;
import form.formDSL.Type;
import java.util.Arrays;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class FormDSLGenerator extends AbstractGenerator {
  private String formClass = "form-control form-control-sm";
  
  private boolean isRequired = true;
  
  private boolean hasFocus = false;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final Form form = Iterators.<Form>filter(resource.getAllContents(), Form.class).next();
    fsa.generateFile("someFile.html", this.compileClass(form));
  }
  
  protected CharSequence _compute(final Input input) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<label class=\"form-label\">");
    CharSequence _compute = this.compute(input.getName());
    _builder.append(_compute);
    _builder.append(":</label>");
    _builder.newLineIfNotEmpty();
    CharSequence _compute_1 = this.compute(input.getType(), input.getName());
    _builder.append(_compute_1);
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _compute(final Generic type, final Name name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<input class=\"");
    _builder.append(this.formClass);
    _builder.append("\" type=\"");
    String _text = type.getText();
    _builder.append(_text);
    _builder.append("\" id=\"");
    _builder.append(name);
    _builder.append("\" placeholder=\"");
    String _text_1 = name.getText();
    _builder.append(_text_1);
    _builder.append("\">");
    return _builder;
  }
  
  protected CharSequence _compute(final LongText type, final Name name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<textarea class=\"");
    _builder.append(this.formClass);
    _builder.append("\" id=\"");
    _builder.append(name);
    _builder.append("\" rows=\"8\" cols=\"50\" placeholder=\"");
    String _text = name.getText();
    _builder.append(_text);
    _builder.append("\"></textarea>");
    return _builder;
  }
  
  protected CharSequence _compute(final Money type, final Name name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<input class=\"");
    _builder.append(this.formClass);
    _builder.append("\" type=\"number\" min=\"0.00\" max=\"10000.00\" step=\"0.01\" placeholder=\"0.00\" id=\"");
    _builder.append(name);
    _builder.append("\">");
    return _builder;
  }
  
  protected CharSequence _compute(final ShortText type, final Name name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<input class=\"");
    _builder.append(this.formClass);
    _builder.append("\" type=\"text\" id=\"");
    _builder.append(name);
    _builder.append("\" placeholder=\"");
    String _text = name.getText();
    _builder.append(_text);
    _builder.append("\">");
    return _builder;
  }
  
  protected CharSequence _compute(final StringNumber type, final Name name) {
    StringConcatenation _builder = new StringConcatenation();
    return _builder;
  }
  
  protected CharSequence _compute(final Name name) {
    return name.getText();
  }
  
  protected String _compute(final Type type) {
    return type.getText();
  }
  
  public CharSequence compileClass(final Form form) {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _startHTML = this.startHTML();
    _builder.append(_startHTML);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("<form onSubmit=\"submitHandler(event)\">");
    _builder.newLine();
    {
      EList<Input> _content = form.getContent();
      for(final Input input : _content) {
        _builder.append("\t");
        CharSequence _compute = this.compute(input);
        _builder.append(_compute, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("<br>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<input type=\"submit\" class=\"btn btn-primary\" value=\"Submit\" onclick=\"submitHandler(event)\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<p style=\"color:red\" id=\"error_output\"></p>");
    _builder.newLine();
    _builder.append("</form>");
    _builder.newLine();
    _builder.newLine();
    CharSequence _compilejs = this.compilejs(form);
    _builder.append(_compilejs);
    _builder.newLineIfNotEmpty();
    CharSequence _endHTML = this.endHTML();
    _builder.append(_endHTML);
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _handleExp(final Optional exp, final Name name) {
    CharSequence _xblockexpression = null;
    {
      this.isRequired = false;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\t\t");
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }
  
  protected CharSequence _handleExp(final Focus exp, final Name name) {
    CharSequence _xblockexpression = null;
    {
      this.hasFocus = true;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\t\t");
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }
  
  protected CharSequence _handleExp(final Is exp, final Name name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("if(!(document.getElementById(\"");
    _builder.append(name);
    _builder.append("\").value ");
    CharSequence _compText = this.getCompText(exp.getComp());
    _builder.append(_compText);
    _builder.append(" ");
    int _value = exp.getValue();
    _builder.append(_value);
    _builder.append(")){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("console.log(\"");
    String _text = name.getText();
    _builder.append(_text, "\t");
    _builder.append(" property failed: \" + document.getElementById(\"");
    _builder.append(name, "\t");
    _builder.append("\").value);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("document.getElementById(\"error_output\").innerHTML = \"\'");
    String _text_1 = name.getText();
    _builder.append(_text_1, "\t");
    _builder.append("\' field was incorrent, \'");
    String _text_2 = name.getText();
    _builder.append(_text_2, "\t");
    _builder.append("\' must be ");
    CharSequence _compText_1 = this.getCompText(exp.getComp());
    _builder.append(_compText_1, "\t");
    _builder.append(" ");
    int _value_1 = exp.getValue();
    _builder.append(_value_1, "\t");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("failedProperty = true;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _handleExp(final Length exp, final Name name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("size");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _getCompText(final GreaterThan comp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(">");
    return _builder;
  }
  
  protected CharSequence _getCompText(final GreaterThanInclusive comp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(">=");
    return _builder;
  }
  
  protected CharSequence _getCompText(final LessThan comp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<");
    return _builder;
  }
  
  protected CharSequence _getCompText(final LessThanInclusive comp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<=");
    return _builder;
  }
  
  protected CharSequence _getCompText(final Exactly comp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("==");
    return _builder;
  }
  
  protected CharSequence _getCompText(final Not comp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("!=");
    return _builder;
  }
  
  private List<String> validators = CollectionLiterals.<String>newArrayList();
  
  public CharSequence compilejs(final Form form) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<script>");
    _builder.newLine();
    _builder.append("//Set focus and required attributes to inputs");
    _builder.newLine();
    {
      EList<Input> _content = form.getContent();
      for(final Input input : _content) {
        {
          EList<Expression> _expression = input.getExpression();
          for(final Expression exp : _expression) {
            _builder.append(this.isRequired = true);
            _builder.newLineIfNotEmpty();
            _builder.append(this.hasFocus = false);
            _builder.newLineIfNotEmpty();
            _builder.append("//");
            boolean _add = this.validators.add(this.handleExp(exp, input.getName()).toString());
            _builder.append(_add);
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.newLine();
        {
          if (this.isRequired) {
            _builder.append("document.getElementById(\"");
            Name _name = input.getName();
            _builder.append(_name);
            _builder.append("\").required = true;");
            _builder.newLineIfNotEmpty();
          }
        }
        {
          if (this.hasFocus) {
            _builder.append("document.getElementById(\"");
            Name _name_1 = input.getName();
            _builder.append(_name_1);
            _builder.append("\").focus();");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.newLine();
    _builder.append("function submitHandler(e){");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("console.log(\"Called submit!\");");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("var failedProperty = false;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("//When submit");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("//foreach expression");
    _builder.newLine();
    {
      for(final String validation : this.validators) {
        _builder.append("\t\t");
        _builder.append(validation, "\t\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t");
    _builder.append("if (failedProperty){");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("console.log(\"Form has failed properties...\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("e.preventDefault();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}else{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("//Submit");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("document.getElementById(\"error_output\").innerHTML = \"\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("console.log(\"Submit!\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("</script>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence startHTML() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<style>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("input{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("height:45px;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("width:100%;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</style>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<title>Form page demo</title>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6\" crossorigin=\"anonymous\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf\" crossorigin=\"anonymous\"></script>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</head>");
    _builder.newLine();
    _builder.append("<body style=\"background-color:#FEFEFE\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf\" crossorigin=\"anonymous\"></script>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div style=\"margin:0 auto; width: 38%; background-color:#FFF; padding:5%; padding-top:6%\">");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence endHTML() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compute(final EObject input) {
    if (input instanceof Input) {
      return _compute((Input)input);
    } else if (input instanceof Name) {
      return _compute((Name)input);
    } else if (input instanceof Type) {
      return _compute((Type)input);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(input).toString());
    }
  }
  
  public CharSequence compute(final Type type, final Name name) {
    if (type instanceof Generic) {
      return _compute((Generic)type, name);
    } else if (type instanceof LongText) {
      return _compute((LongText)type, name);
    } else if (type instanceof Money) {
      return _compute((Money)type, name);
    } else if (type instanceof ShortText) {
      return _compute((ShortText)type, name);
    } else if (type instanceof StringNumber) {
      return _compute((StringNumber)type, name);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(type, name).toString());
    }
  }
  
  public CharSequence handleExp(final Expression exp, final Name name) {
    if (exp instanceof Is) {
      return _handleExp((Is)exp, name);
    } else if (exp instanceof Length) {
      return _handleExp((Length)exp, name);
    } else if (exp instanceof Focus) {
      return _handleExp((Focus)exp, name);
    } else if (exp instanceof Optional) {
      return _handleExp((Optional)exp, name);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(exp, name).toString());
    }
  }
  
  public CharSequence getCompText(final Comparison comp) {
    if (comp instanceof Exactly) {
      return _getCompText((Exactly)comp);
    } else if (comp instanceof GreaterThan) {
      return _getCompText((GreaterThan)comp);
    } else if (comp instanceof GreaterThanInclusive) {
      return _getCompText((GreaterThanInclusive)comp);
    } else if (comp instanceof LessThan) {
      return _getCompText((LessThan)comp);
    } else if (comp instanceof LessThanInclusive) {
      return _getCompText((LessThanInclusive)comp);
    } else if (comp instanceof Not) {
      return _getCompText((Not)comp);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(comp).toString());
    }
  }
}
