/**
 * generated by Xtext 2.24.0
 */
package form.tests;

import com.google.inject.Inject;
import form.tests.FormDSLInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(FormDSLInjectorProvider.class)
@SuppressWarnings("all")
public class FormDSLParsingTest {
  @Inject
  @Test
  public void loadModel() {
  }
}
