/*
 * generated by Xtext 2.24.0
 */
package form.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import form.FormDSLRuntimeModule;
import form.FormDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FormDSLIdeSetup extends FormDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FormDSLRuntimeModule(), new FormDSLIdeModule()));
	}
	
}
