/*
 * generated by Xtext 2.24.0
 */
package form.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFormDSLScopeProvider extends DelegatingScopeProvider {
}
