/*
 * generated by Xtext 2.24.0
 */
package form.parser.antlr;

import com.google.inject.Inject;
import form.parser.antlr.internal.InternalFormDSLParser;
import form.services.FormDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FormDSLParser extends AbstractAntlrParser {

	@Inject
	private FormDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFormDSLParser createParser(XtextTokenStream stream) {
		return new InternalFormDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Form";
	}

	public FormDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FormDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
