/*
 * generated by Xtext 2.24.0
 */
package form.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import form.ide.contentassist.antlr.internal.InternalFormDSLParser;
import form.services.FormDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class FormDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(FormDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, FormDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getFormAccess().getGroup(), "rule__Form__Group__0");
			builder.put(grammarAccess.getInputAccess().getGroup(), "rule__Input__Group__0");
			builder.put(grammarAccess.getFormAccess().getContentAssignment_2(), "rule__Form__ContentAssignment_2");
			builder.put(grammarAccess.getInputAccess().getTypeAssignment_0(), "rule__Input__TypeAssignment_0");
			builder.put(grammarAccess.getInputAccess().getNameAssignment_1(), "rule__Input__NameAssignment_1");
			builder.put(grammarAccess.getInputAccess().getExpressionAssignment_2(), "rule__Input__ExpressionAssignment_2");
			builder.put(grammarAccess.getTypeAccess().getTextAssignment_0(), "rule__Type__TextAssignment_0");
			builder.put(grammarAccess.getTypeAccess().getTextAssignment_1(), "rule__Type__TextAssignment_1");
			builder.put(grammarAccess.getTypeAccess().getTextAssignment_2(), "rule__Type__TextAssignment_2");
			builder.put(grammarAccess.getTypeAccess().getTextAssignment_3(), "rule__Type__TextAssignment_3");
			builder.put(grammarAccess.getTypeAccess().getTextAssignment_4(), "rule__Type__TextAssignment_4");
			builder.put(grammarAccess.getTypeAccess().getTextAssignment_5(), "rule__Type__TextAssignment_5");
			builder.put(grammarAccess.getTypeAccess().getTextAssignment_6(), "rule__Type__TextAssignment_6");
			builder.put(grammarAccess.getNameAccess().getTextAssignment(), "rule__Name__TextAssignment");
			builder.put(grammarAccess.getExpressionAccess().getTextAssignment_0(), "rule__Expression__TextAssignment_0");
			builder.put(grammarAccess.getExpressionAccess().getTextAssignment_1(), "rule__Expression__TextAssignment_1");
			builder.put(grammarAccess.getExpressionAccess().getTextAssignment_2(), "rule__Expression__TextAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private FormDSLGrammarAccess grammarAccess;

	@Override
	protected InternalFormDSLParser createParser() {
		InternalFormDSLParser result = new InternalFormDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FormDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FormDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
