/*
 * generated by Xtext 2.24.0
 */
package form.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FormDSLUiModule extends AbstractFormDSLUiModule {

	public FormDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
