/**
 * generated by Xtext 2.25.0
 */
package form.formDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getComparison()
 * @model
 * @generated
 */
public interface Comparison extends EObject
{
} // Comparison
