/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Form</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link form.formDSL.Form#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see form.formDSL.FormDSLPackage#getForm()
 * @model
 * @generated
 */
public interface Form extends EObject
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference list.
   * The list contents are of type {@link form.formDSL.Input}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference list.
   * @see form.formDSL.FormDSLPackage#getForm_Content()
   * @model containment="true"
   * @generated
   */
  EList<Input> getContent();

} // Form
