/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greater Than Inclusive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getGreaterThanInclusive()
 * @model
 * @generated
 */
public interface GreaterThanInclusive extends Comparison
{
} // GreaterThanInclusive
