/**
 * generated by Xtext 2.25.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Is</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getIs()
 * @model
 * @generated
 */
public interface Is extends Exp
{
} // Is
