/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Less Than</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getLessThan()
 * @model
 * @generated
 */
public interface LessThan extends Comparison
{
} // LessThan
