/**
 * generated by Xtext 2.25.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Less Thaninclusive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getLessThaninclusive()
 * @model
 * @generated
 */
public interface LessThaninclusive extends Comparison
{
} // LessThaninclusive
