/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Less Than Inclusive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getLessThanInclusive()
 * @model
 * @generated
 */
public interface LessThanInclusive extends Comparison
{
} // LessThanInclusive
