/**
 * generated by Xtext 2.25.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Long Text</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getLongText()
 * @model
 * @generated
 */
public interface LongText extends Type
{
} // LongText
