/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Money</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getMoney()
 * @model
 * @generated
 */
public interface Money extends Type
{
} // Money
