/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getNot()
 * @model
 * @generated
 */
public interface Not extends Comparison
{
} // Not
