/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Optional</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getOptional()
 * @model
 * @generated
 */
public interface Optional extends Expression
{
} // Optional
