/**
 * generated by Xtext 2.24.0
 */
package form.formDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see form.formDSL.FormDSLPackage#getStringNumber()
 * @model
 * @generated
 */
public interface StringNumber extends Type
{
} // StringNumber
