/**
 * generated by Xtext 2.25.0
 */
package form.formDSL.impl;

import form.formDSL.Exactly;
import form.formDSL.FormDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exactly</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExactlyImpl extends ComparisonImpl implements Exactly
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExactlyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.EXACTLY;
  }

} //ExactlyImpl
