/**
 * generated by Xtext 2.25.0
 */
package form.formDSL.impl;

import form.formDSL.Focus;
import form.formDSL.FormDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Focus</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FocusImpl extends ExpressionImpl implements Focus
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FocusImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.FOCUS;
  }

} //FocusImpl
