/**
 * generated by Xtext 2.24.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.GreaterThan;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Greater Than</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GreaterThanImpl extends ComparisonImpl implements GreaterThan
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GreaterThanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.GREATER_THAN;
  }

} //GreaterThanImpl
