/**
 * generated by Xtext 2.25.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.GreaterThaninclusive;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Greater Thaninclusive</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GreaterThaninclusiveImpl extends ComparisonImpl implements GreaterThaninclusive
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GreaterThaninclusiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.GREATER_THANINCLUSIVE;
  }

} //GreaterThaninclusiveImpl
