/**
 * generated by Xtext 2.25.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.GreaterThanInclusive;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Greater Than Inclusive</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GreaterThanInclusiveImpl extends ComparisonImpl implements GreaterThanInclusive
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GreaterThanInclusiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.GREATER_THAN_INCLUSIVE;
  }

} //GreaterThanInclusiveImpl
