/**
 * generated by Xtext 2.25.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.Is;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Is</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IsImpl extends ExpImpl implements Is
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.IS;
  }

} //IsImpl
