/**
 * generated by Xtext 2.25.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.Length;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Length</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LengthImpl extends ExpImpl implements Length
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LengthImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.LENGTH;
  }

} //LengthImpl
