/**
 * generated by Xtext 2.24.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.LessThanInclusive;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Less Than Inclusive</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LessThanInclusiveImpl extends ComparisonImpl implements LessThanInclusive
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LessThanInclusiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.LESS_THAN_INCLUSIVE;
  }

} //LessThanInclusiveImpl
