/**
 * generated by Xtext 2.24.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.LongText;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Long Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LongTextImpl extends TypeImpl implements LongText
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LongTextImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.LONG_TEXT;
  }

} //LongTextImpl
