/**
 * generated by Xtext 2.25.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.Optional;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Optional</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OptionalImpl extends ExpressionImpl implements Optional
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OptionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.OPTIONAL;
  }

} //OptionalImpl
