/**
 * generated by Xtext 2.24.0
 */
package form.formDSL.impl;

import form.formDSL.FormDSLPackage;
import form.formDSL.StringNumber;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StringNumberImpl extends TypeImpl implements StringNumber
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StringNumberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormDSLPackage.Literals.STRING_NUMBER;
  }

} //StringNumberImpl
